[package]
name = "compilazione_auto_ts"
version = "0.1.0"
edition = "2024"

[dependencies]
rust_xlsxwriter = "0.86.1"
chrono = "0.4"
once_cell = "1.21.3"
serde_json = "1.0.140"
serde = {version = "1.0.219" , features = ["derive"] }
rfd = "0.15.3"